import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// One sidebar per top-level section. Each is autogenerated from its folder so
// adding a topic file is all it takes to add a page. Ordering comes from
// `sidebar_position` frontmatter and `_category_.json`.
const sidebars: SidebarsConfig = {
  foundationsSidebar: [{type: 'autogenerated', dirName: 'foundations'}],
  backendSidebar: [{type: 'autogenerated', dirName: 'backend'}],
  dataEngineeringSidebar: [{type: 'autogenerated', dirName: 'data-engineering'}],
  appendixSidebar: [{type: 'autogenerated', dirName: 'appendix'}],
};

export default sidebars;
